/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AllocationRouteImport } from './routes/allocation'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as DecisionsRouteImport } from './routes/decisions'
import { Route as DispatchRouteImport } from './routes/dispatch'
import { Route as ExceptionsRouteImport } from './routes/exceptions'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as PackingRouteImport } from './routes/packing'
import { Route as PickingRouteImport } from './routes/picking'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AllocationRoute = AllocationRouteImport.update({
  id: '/allocation',
  path: '/allocation',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionsRoute = DecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchRoute = DispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const ExceptionsRoute = ExceptionsRouteImport.update({
  id: '/exceptions',
  path: '/exceptions',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const PackingRoute = PackingRouteImport.update({
  id: '/packing',
  path: '/packing',
  getParentRoute: () => rootRouteImport,
} as any)
const PickingRoute = PickingRouteImport.update({
  id: '/picking',
  path: '/picking',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/allocation': typeof AllocationRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/decisions': typeof DecisionsRoute
  '/dispatch': typeof DispatchRoute
  '/exceptions': typeof ExceptionsRoute
  '/inventory': typeof InventoryRoute
  '/packing': typeof PackingRoute
  '/picking': typeof PickingRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/': typeof OrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/allocation': typeof AllocationRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/decisions': typeof DecisionsRoute
  '/dispatch': typeof DispatchRoute
  '/exceptions': typeof ExceptionsRoute
  '/inventory': typeof InventoryRoute
  '/packing': typeof PackingRoute
  '/picking': typeof PickingRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders': typeof OrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/allocation': typeof AllocationRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/decisions': typeof DecisionsRoute
  '/dispatch': typeof DispatchRoute
  '/exceptions': typeof ExceptionsRoute
  '/inventory': typeof InventoryRoute
  '/packing': typeof PackingRoute
  '/picking': typeof PickingRoute
  '/settings': typeof SettingsRoute
  '/simulator': typeof SimulatorRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/orders/': typeof OrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/allocation'
    | '/analytics'
    | '/assistant'
    | '/decisions'
    | '/dispatch'
    | '/exceptions'
    | '/inventory'
    | '/packing'
    | '/picking'
    | '/settings'
    | '/simulator'
    | '/orders/$orderId'
    | '/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/allocation'
    | '/analytics'
    | '/assistant'
    | '/decisions'
    | '/dispatch'
    | '/exceptions'
    | '/inventory'
    | '/packing'
    | '/picking'
    | '/settings'
    | '/simulator'
    | '/orders/$orderId'
    | '/orders'
  id:
    | '__root__'
    | '/'
    | '/allocation'
    | '/analytics'
    | '/assistant'
    | '/decisions'
    | '/dispatch'
    | '/exceptions'
    | '/inventory'
    | '/packing'
    | '/picking'
    | '/settings'
    | '/simulator'
    | '/orders/$orderId'
    | '/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllocationRoute: typeof AllocationRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AssistantRoute: typeof AssistantRoute
  DecisionsRoute: typeof DecisionsRoute
  DispatchRoute: typeof DispatchRoute
  ExceptionsRoute: typeof ExceptionsRoute
  InventoryRoute: typeof InventoryRoute
  PackingRoute: typeof PackingRoute
  PickingRoute: typeof PickingRoute
  SettingsRoute: typeof SettingsRoute
  SimulatorRoute: typeof SimulatorRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/allocation': {
      id: '/allocation'
      path: '/allocation'
      fullPath: '/allocation'
      preLoaderRoute: typeof AllocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decisions': {
      id: '/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof DecisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch': {
      id: '/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof DispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exceptions': {
      id: '/exceptions'
      path: '/exceptions'
      fullPath: '/exceptions'
      preLoaderRoute: typeof ExceptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packing': {
      id: '/packing'
      path: '/packing'
      fullPath: '/packing'
      preLoaderRoute: typeof PackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/picking': {
      id: '/picking'
      path: '/picking'
      fullPath: '/picking'
      preLoaderRoute: typeof PickingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllocationRoute: AllocationRoute,
  AnalyticsRoute: AnalyticsRoute,
  AssistantRoute: AssistantRoute,
  DecisionsRoute: DecisionsRoute,
  DispatchRoute: DispatchRoute,
  ExceptionsRoute: ExceptionsRoute,
  InventoryRoute: InventoryRoute,
  PackingRoute: PackingRoute,
  PickingRoute: PickingRoute,
  SettingsRoute: SettingsRoute,
  SimulatorRoute: SimulatorRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
